// user 액션 타입 정의
export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCES = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// cart 액션 타입 정의
export const LOAD_WISH_REQUEST = 'LOAD_WISH_REQUEST';
export const LOAD_WISH_SUCCESS = 'LOAD_WISH_SUCCESS';
export const LOAD_WISH_FAILURE = 'LOAD_WISH_FAILURE';

export const ADD_WISH_REQUEST = 'ADD_WISH_REQUEST';
export const ADD_WISH_SUCCESS = 'ADD_WISH_SUCCESS';
export const ADD_WISH_FAILURE = 'ADD_WISH_FAILURE';

export const REMOVE_WISH_REQUSET = 'REMOVE_WISH_REQUSET';
export const REMOVE_WISH_SUCCESS = 'REMOVE_WISH_SUCCESS';
export const REMOVE_WISH_FAILURE = 'REMOVE_WISH_FAILURE';

export const UPLOAD_IMG_REQUEST = 'UPLOAD_IMG_REQUEST';
export const UPLOAD_IMG_SUCCESS = 'UPLOAD_IMG_SUCCESS';
export const UPLOAD_IMG_FAILURE = 'UPLOAD_IMG_FAILURE';

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const LOAD_REVIEW_LIST_REQUEST = 'LOAD_REVIEW_LIST_REQUEST';
export const LOAD_REVIEW_LIST_SUCCESS = 'LOAD_REVIEW_LIST_SUCCESS';
export const LOAD_REVIEW_LIST_FAILURE = 'LOAD_REVIEW_LIST_FAILURE';

export const LOAD_USER_INFO_REQUEST = 'LOAD_USER_INFO_REQUEST';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAILURE = 'LOAD_USER_INFO_FAILURE';
